name: Build and Upload Flutter App

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Setup Firebase for Flutter
        run: |
          npm install -g firebase-tools
          dart pub global activate flutterfire_cli
          flutterfire configure --project=simple-flutter-form --token=${{ secrets.FIREBASE_TOKEN }} --yes --platforms=android,ios,macos,web,linux,windows

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-release.apk
